name: mattconahan.com
favicon: null
layout_spectrum: 0.010147801833227277
typography_spectrum: 0.6191765945404768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.338295633206144
  lightness: 0.16867811465635896
  saturation: 0.23731973045505583
  rhythmicContrast: 0.2459181840531528
purpose: []
